# Generated by Django 5.0.4 on 2024-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='affiches/'),
        ),
    ]
